import type { AggregateDemandArea } from "./types";

// Generated by scripts/fetch-demand-data.mjs from SCB open data.
// residents: SCB population by DeSO 2025, 2025.
// employedResidents: SCB BAS employed residents by DeSO 2025, 2024.
// jobs: SCB RAMS workplace employment by municipality, 2021, distributed to display areas by job-center weights.
export const aggregateDemandAreas: AggregateDemandArea[] = [
  {
    "id": "inner-city",
    "name": "Inner city",
    "bounds": {
      "south": 59.315,
      "west": 18.025,
      "north": 59.355,
      "east": 18.11
    },
    "residents": 37880,
    "employedResidents": 22115,
    "jobs": 215086
  },
  {
    "id": "sodermalm",
    "name": "Sodermalm",
    "bounds": {
      "south": 59.295,
      "west": 18.005,
      "north": 59.33,
      "east": 18.11
    },
    "residents": 139991,
    "employedResidents": 81392,
    "jobs": 55150
  },
  {
    "id": "kungsholmen",
    "name": "Kungsholmen",
    "bounds": {
      "south": 59.318,
      "west": 17.995,
      "north": 59.348,
      "east": 18.06
    },
    "residents": 132423,
    "employedResidents": 78847,
    "jobs": 49635
  },
  {
    "id": "vasastan",
    "name": "Vasastan",
    "bounds": {
      "south": 59.33,
      "west": 18.02,
      "north": 59.365,
      "east": 18.08
    },
    "residents": 46197,
    "employedResidents": 24627,
    "jobs": 71695
  },
  {
    "id": "ostermalm-gardet",
    "name": "Ostermalm and Gardet",
    "bounds": {
      "south": 59.33,
      "west": 18.065,
      "north": 59.37,
      "east": 18.145
    },
    "residents": 68491,
    "employedResidents": 35460,
    "jobs": 83644
  },
  {
    "id": "solna-sundbyberg",
    "name": "Solna and Sundbyberg",
    "bounds": {
      "south": 59.34,
      "west": 17.94,
      "north": 59.39,
      "east": 18.04
    },
    "residents": 80194,
    "employedResidents": 45140,
    "jobs": 132510
  },
  {
    "id": "hagersten-liljeholmen",
    "name": "Hagersten and Liljeholmen",
    "bounds": {
      "south": 59.28,
      "west": 17.95,
      "north": 59.325,
      "east": 18.04
    },
    "residents": 46312,
    "employedResidents": 26545,
    "jobs": 36767
  },
  {
    "id": "soderort-west",
    "name": "Western Soderort",
    "bounds": {
      "south": 59.255,
      "west": 17.94,
      "north": 59.31,
      "east": 17.99
    },
    "residents": 55497,
    "employedResidents": 30014,
    "jobs": 29413
  },
  {
    "id": "soderort-east",
    "name": "Eastern Soderort",
    "bounds": {
      "south": 59.255,
      "west": 18.03,
      "north": 59.31,
      "east": 18.155
    },
    "residents": 23268,
    "employedResidents": 12763,
    "jobs": 31252
  },
  {
    "id": "kista-jarva",
    "name": "Kista and Jarva",
    "bounds": {
      "south": 59.375,
      "west": 17.91,
      "north": 59.42,
      "east": 17.98
    },
    "residents": 13769,
    "employedResidents": 7144,
    "jobs": 52393
  },
  {
    "id": "bromma-vasterort",
    "name": "Bromma and Vasterort",
    "bounds": {
      "south": 59.325,
      "west": 17.94,
      "north": 59.38,
      "east": 17.98
    },
    "residents": 73178,
    "employedResidents": 42399,
    "jobs": 31252
  },
  {
    "id": "lidingo",
    "name": "Lidingo",
    "bounds": {
      "south": 59.345,
      "west": 18.1,
      "north": 59.42,
      "east": 18.2
    },
    "residents": 23924,
    "employedResidents": 11688,
    "jobs": 12196
  },
  {
    "id": "nacka",
    "name": "Nacka",
    "bounds": {
      "south": 59.26,
      "west": 18.08,
      "north": 59.35,
      "east": 18.2
    },
    "residents": 32032,
    "employedResidents": 16769,
    "jobs": 36300
  },
  {
    "id": "farsta-skarpnack",
    "name": "Farsta and Skarpnack",
    "bounds": {
      "south": 59.255,
      "west": 18.04,
      "north": 59.3,
      "east": 18.15
    },
    "residents": 114756,
    "employedResidents": 63347,
    "jobs": 20222
  },
  {
    "id": "akalla-tensta",
    "name": "Akalla and Tensta",
    "bounds": {
      "south": 59.38,
      "west": 17.9,
      "north": 59.42,
      "east": 17.955
    },
    "residents": 79430,
    "employedResidents": 36066,
    "jobs": 12868
  },
  {
    "id": "bromma-south",
    "name": "Southern Bromma",
    "bounds": {
      "south": 59.3,
      "west": 17.92,
      "north": 59.34,
      "east": 17.98
    },
    "residents": 20568,
    "employedResidents": 10183,
    "jobs": 23898
  }
];
