import type { AggregateDemandArea } from "./types";

// Generated by scripts/fetch-demand-data.mjs from SCB open data.
// residents: SCB population by DeSO 2025, 2025.
// employedResidents: SCB BAS employed residents by DeSO 2025, 2024.
// jobs: SCB RAMS workplace employment by municipality, 2021, distributed to display areas by job-center weights.
export const aggregateDemandAreas: AggregateDemandArea[] = [
  {
    "id": "inner-city",
    "name": "Inner city",
    "bounds": {
      "south": 59.318,
      "west": 18.028,
      "north": 59.351,
      "east": 18.101
    },
    "residents": 3561,
    "employedResidents": 1938,
    "jobs": 234033
  },
  {
    "id": "sodermalm",
    "name": "Sodermalm",
    "bounds": {
      "south": 59.3,
      "west": 18.01,
      "north": 59.325,
      "east": 18.1
    },
    "residents": 143742,
    "employedResidents": 82776,
    "jobs": 59823
  },
  {
    "id": "kungsholmen",
    "name": "Kungsholmen",
    "bounds": {
      "south": 59.321,
      "west": 18,
      "north": 59.343,
      "east": 18.055
    },
    "residents": 89147,
    "employedResidents": 53640,
    "jobs": 53906
  },
  {
    "id": "vasastan",
    "name": "Vasastan",
    "bounds": {
      "south": 59.335,
      "west": 18.025,
      "north": 59.36,
      "east": 18.075
    },
    "residents": 63367,
    "employedResidents": 36240,
    "jobs": 77573
  },
  {
    "id": "ostermalm-gardet",
    "name": "Ostermalm and Gardet",
    "bounds": {
      "south": 59.332,
      "west": 18.07,
      "north": 59.365,
      "east": 18.135
    },
    "residents": 69858,
    "employedResidents": 35776,
    "jobs": 91378
  },
  {
    "id": "solna-sundbyberg",
    "name": "Solna and Sundbyberg",
    "bounds": {
      "south": 59.345,
      "west": 17.95,
      "north": 59.385,
      "east": 18.03
    },
    "residents": 125269,
    "employedResidents": 72087,
    "jobs": 132510
  },
  {
    "id": "hagersten-liljeholmen",
    "name": "Hagersten and Liljeholmen",
    "bounds": {
      "south": 59.285,
      "west": 17.955,
      "north": 59.318,
      "east": 18.03
    },
    "residents": 72100,
    "employedResidents": 41813,
    "jobs": 40101
  },
  {
    "id": "soderort-west",
    "name": "Western Soderort",
    "bounds": {
      "south": 59.245,
      "west": 17.885,
      "north": 59.305,
      "east": 17.985
    },
    "residents": 80219,
    "employedResidents": 39437,
    "jobs": 31555
  },
  {
    "id": "soderort-east",
    "name": "Eastern Soderort",
    "bounds": {
      "south": 59.24,
      "west": 18.035,
      "north": 59.305,
      "east": 18.145
    },
    "residents": 179877,
    "employedResidents": 99759,
    "jobs": 34185
  },
  {
    "id": "kista-jarva",
    "name": "Kista and Jarva",
    "bounds": {
      "south": 59.385,
      "west": 17.885,
      "north": 59.42,
      "east": 17.965
    },
    "residents": 80310,
    "employedResidents": 35817,
    "jobs": 57193
  },
  {
    "id": "bromma-vasterort",
    "name": "Bromma and Vasterort",
    "bounds": {
      "south": 59.33,
      "west": 17.825,
      "north": 59.375,
      "east": 17.97
    },
    "residents": 113562,
    "employedResidents": 59569,
    "jobs": 33527
  }
];
